var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(panels)/student/profile-360/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0u8u8tq._.js")
R.c("server/chunks/ssr/0f64_next_dist_00qh9.l._.js")
R.c("server/chunks/ssr/0f64_next_dist_esm_build_templates_app-page_122xc25.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qruci7._.js")
R.c("server/chunks/ssr/0f64_next_dist_12zai6s._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0wthae9._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0nmz3ov._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_0.duttl._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_unauthorized_0np8kb1.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_global-error_0lsrb8j.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_src_app_(panels)_student_layout_tsx_0sipqh6._.js")
R.c("server/chunks/ssr/0k~b__next-internal_server_app_(panels)_student_profile-360_page_actions_078629k.js")
R.m(29873)
module.exports=R.m(29873).exports
