var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(panels)/student/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00..4t~._.js")
R.c("server/chunks/ssr/0f64_next_dist_00qh9.l._.js")
R.c("server/chunks/ssr/0f64_next_dist_esm_build_templates_app-page_02_qvl_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qruci7._.js")
R.c("server/chunks/ssr/0f64_next_dist_12zai6s._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0wthae9._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0nmz3ov._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_0.duttl._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_unauthorized_0np8kb1.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_global-error_0lsrb8j.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_src_app_(panels)_student_layout_tsx_0sipqh6._.js")
R.c("server/chunks/ssr/08b0_Check__next-internal_server_app_(panels)_student_dashboard_page_actions_0a152in.js")
R.m(29004)
module.exports=R.m(29004).exports
