var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e3.3qf._.js")
R.c("server/chunks/ssr/0f64_next_dist_00qh9.l._.js")
R.c("server/chunks/ssr/0f64_next_dist_esm_build_templates_app-page_0ei0pkb.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qruci7._.js")
R.c("server/chunks/ssr/0f64_next_dist_12zai6s._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0wthae9._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0nmz3ov._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_0.duttl._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_unauthorized_0np8kb1.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check__next-internal_server_app__not-found_page_actions_006nmi~.js")
R.m(52524)
module.exports=R.m(52524).exports
