var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reports/generate/route.js")
R.c("server/chunks/[root-of-the-server]__0ik1_pe._.js")
R.c("server/chunks/Desktop_Egitim_Check_03cfjnn._.js")
R.c("server/chunks/Desktop_Egitim_Check_06tlm5k._.js")
R.c("server/chunks/0f64_next_dist_0b64icw._.js")
R.c("server/chunks/0f64_0jsureg._.js")
R.c("server/chunks/[root-of-the-server]__0caz6b8._.js")
R.c("server/chunks/Desktop_Egitim_Check_src_lib_ai_claude-client_ts_0zl03ti._.js")
R.c("server/chunks/08b0_Check__next-internal_server_app_api_reports_generate_route_actions_0pd05br.js")
R.m(92367)
module.exports=R.m(92367).exports
