var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(panels)/teacher/reports/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bcr5s.._.js")
R.c("server/chunks/ssr/0f64_next_dist_00qh9.l._.js")
R.c("server/chunks/ssr/0f64_next_dist_esm_build_templates_app-page_109-h0c.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qruci7._.js")
R.c("server/chunks/ssr/0f64_next_dist_12zai6s._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0wthae9._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0nmz3ov._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_0.duttl._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_unauthorized_0np8kb1.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_global-error_0lsrb8j.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_src_app_(panels)_teacher_layout_tsx_0p.yagb._.js")
R.c("server/chunks/ssr/08b0_Check__next-internal_server_app_(panels)_teacher_reports_page_actions_0zzy_3j.js")
R.m(78915)
module.exports=R.m(78915).exports
