// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/dashboard" | "/admin/licenses" | "/admin/schools" | "/admin/settings" | "/admin/users" | "/kvkk" | "/login" | "/parent/dashboard" | "/parent/my-children" | "/parent/results" | "/register" | "/school/billing" | "/school/classes" | "/school/dashboard" | "/school/parents" | "/school/students" | "/school/teachers" | "/student/dashboard" | "/student/my-results" | "/student/my-tests" | "/student/my-tests/[testId]" | "/student/profile" | "/student/profile-360" | "/teacher/assign-test" | "/teacher/dashboard" | "/teacher/my-classes" | "/teacher/reports" | "/teacher/results"
type AppRouteHandlerRoutes = "/api/admin/assign-teacher-classes" | "/api/admin/create-teacher" | "/api/admin/reset-teacher-password" | "/api/export/[format]" | "/api/payment/callback" | "/api/payment/create" | "/api/payment/status" | "/api/reports/generate" | "/api/reports/integrated" | "/api/reports/profile-360"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/parent" | "/school" | "/student" | "/teacher"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/dashboard": {}
  "/admin/licenses": {}
  "/admin/schools": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/admin/assign-teacher-classes": {}
  "/api/admin/create-teacher": {}
  "/api/admin/reset-teacher-password": {}
  "/api/export/[format]": { "format": string; }
  "/api/payment/callback": {}
  "/api/payment/create": {}
  "/api/payment/status": {}
  "/api/reports/generate": {}
  "/api/reports/integrated": {}
  "/api/reports/profile-360": {}
  "/kvkk": {}
  "/login": {}
  "/parent": {}
  "/parent/dashboard": {}
  "/parent/my-children": {}
  "/parent/results": {}
  "/register": {}
  "/school": {}
  "/school/billing": {}
  "/school/classes": {}
  "/school/dashboard": {}
  "/school/parents": {}
  "/school/students": {}
  "/school/teachers": {}
  "/student": {}
  "/student/dashboard": {}
  "/student/my-results": {}
  "/student/my-tests": {}
  "/student/my-tests/[testId]": { "testId": string; }
  "/student/profile": {}
  "/student/profile-360": {}
  "/teacher": {}
  "/teacher/assign-test": {}
  "/teacher/dashboard": {}
  "/teacher/my-classes": {}
  "/teacher/reports": {}
  "/teacher/results": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/parent": never
  "/school": never
  "/student": never
  "/teacher": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
