// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/admin/licenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/licenses">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/admin/licenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/admin/schools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/schools">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/admin/schools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/parent/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/parent/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/parent/my-children/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/my-children">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/parent/my-children/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/parent/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/results">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/parent/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school/billing">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school/classes">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/parents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school/parents">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/parents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school/students">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/school/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/my-results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/my-results">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/my-results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/my-tests/[testId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/my-tests/[testId]">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/my-tests/[testId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/my-tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/my-tests">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/my-tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/profile-360/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/profile-360">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/profile-360/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/teacher/assign-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/assign-test">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/teacher/assign-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/teacher/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/teacher/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/teacher/my-classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/my-classes">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/teacher/my-classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/teacher/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/teacher/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/teacher/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/results">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/teacher/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kvkk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kvkk">> = Specific
  const handler = {} as typeof import("../../src/app/kvkk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/assign-teacher-classes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/assign-teacher-classes">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/assign-teacher-classes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/create-teacher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-teacher">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/create-teacher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reset-teacher-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset-teacher-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reset-teacher-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/export/[format]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/[format]">> = Specific
  const handler = {} as typeof import("../../src/app/api/export/[format]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/integrated/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/integrated">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/integrated/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/profile-360/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/profile-360">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/profile-360/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(panels)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/parent/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/parent">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/parent/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/school/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/school">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/school/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/student/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/student">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/student/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(panels)/teacher/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/(panels)/teacher/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
