var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(panels)/student/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qjjuxs._.js")
R.c("server/chunks/ssr/0f64_next_dist_00qh9.l._.js")
R.c("server/chunks/ssr/0f64_next_dist_esm_build_templates_app-page_02qw2.7.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qruci7._.js")
R.c("server/chunks/ssr/0f64_next_dist_12zai6s._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0wthae9._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0nmz3ov._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_0.duttl._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_unauthorized_0np8kb1.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_global-error_0lsrb8j.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_src_app_(panels)_student_layout_tsx_0sipqh6._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0kcqze3._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0q~ow01._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_00m_lxe._.js")
R.m(97162)
module.exports=R.m(97162).exports
