var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(panels)/admin/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t2pmsl._.js")
R.c("server/chunks/ssr/0f64_next_dist_esm_build_templates_app-page_0qry75..js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0q~ow01._.js")
R.c("server/chunks/ssr/0f64_next_dist_00qh9.l._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qruci7._.js")
R.c("server/chunks/ssr/0f64_next_dist_12zai6s._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0wthae9._.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_0nmz3ov._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_0.duttl._.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_unauthorized_0np8kb1.js")
R.c("server/chunks/ssr/0f64_next_dist_client_components_builtin_global-error_0lsrb8j.js")
R.c("server/chunks/ssr/Desktop_Egitim_Check_src_app_(panels)_admin_layout_tsx_06ub~b5._.js")
R.c("server/chunks/ssr/08b0_Check__next-internal_server_app_(panels)_admin_dashboard_page_actions_0j2n1hv.js")
R.m(23638)
module.exports=R.m(23638).exports
